# Generated by Django 4.2.7 on 2026-02-23 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=10)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manager', models.ForeignKey(limit_choices_to={'role__name': 'MANAGER'}, on_delete=django.db.models.deletion.CASCADE, related_name='managed_sites', to='auth_app.customuser')),
            ],
            options={
                'verbose_name': 'Site',
                'verbose_name_plural': 'Sites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='sites.site')),
            ],
            options={
                'verbose_name': "Horaires d'ouverture",
                'verbose_name_plural': "Horaires d'ouverture",
                'ordering': ['day_of_week'],
            },
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['city'], name='sites_site_city_35d94a_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['manager'], name='sites_site_manager_068ee5_idx'),
        ),
        migrations.AddIndex(
            model_name='site',
            index=models.Index(fields=['is_active'], name='sites_site_is_acti_2a8915_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='openinghours',
            unique_together={('site', 'day_of_week')},
        ),
    ]
