# Generated by Django 4.2.7 on 2026-02-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_siteimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='openinghours',
            options={'ordering': ['day_of_week']},
        ),
        migrations.AddField(
            model_name='siteimage',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
