# Generated by Django 4.2.7 on 2026-02-23 00:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sport_type', models.CharField(choices=[('TENNIS', 'Tennis'), ('FOOTBALL', 'Football'), ('BASKETBALL', 'Basketball'), ('BADMINTON', 'Badminton'), ('VOLLEYBALL', 'Volleyball'), ('SQUASH', 'Squash'), ('PING_PONG', 'Ping-pong'), ('PADEL', 'Padel'), ('HAND', 'Handball'), ('OTHER', 'Autre')], max_length=50)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('is_active', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CourtImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='courts/images/')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='courts.court')),
            ],
            options={
                'verbose_name': 'Image de terrain',
                'verbose_name_plural': 'Images de terrains',
                'ordering': ['-is_primary', '-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='court',
            name='equipments',
            field=models.ManyToManyField(blank=True, related_name='courts', to='courts.equipment'),
        ),
        migrations.AddField(
            model_name='court',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courts', to='sites.site'),
        ),
        migrations.CreateModel(
            name='BlockedPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('court', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_periods', to='courts.court')),
            ],
            options={
                'verbose_name': 'Période bloquée',
                'verbose_name_plural': 'Périodes bloquées',
                'ordering': ['start_datetime'],
            },
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['site'], name='courts_cour_site_id_15febd_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['sport_type'], name='courts_cour_sport_t_082085_idx'),
        ),
        migrations.AddIndex(
            model_name='court',
            index=models.Index(fields=['is_active'], name='courts_cour_is_acti_bc541b_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedperiod',
            index=models.Index(fields=['court', 'start_datetime'], name='courts_bloc_court_i_2986a6_idx'),
        ),
    ]
